[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
mysolanaapp = "6N9BmKR9aNbGCM8auMBQ8ZfRbkgxpWDJJJA4jvd2sk1Y"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run mocha -t 1000000 tests/"
